import Head from 'next/head';
import Image from 'next/image';
import 'twin.macro';
import tw from 'twin.macro';
import Features from '../components/Features';
import Footer from '../components/Footer';
import Header from '../components/Header';
import Navbar from '../components/Navbar';
import Portfolio from '../components/Portfolio';
import Services from '../components/Services';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <Header />
      <Features />
      <Services />
      <Portfolio />
      <Footer />
    </div>
  );
}
